trigger:
- master
- infra
- dev

stages:
- stage: Prod
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  jobs:
  - deployment: deployprod
    displayName: prod
    environment:
      name: PROD
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: cp index.php /var/www/html/index.php

- stage: Dev
  condition: eq(variables['build.sourceBranch'], 'refs/heads/dev')
  jobs:
  - job: deploydev

- stage: Deploy
  condition: eq(variables['build.sourceBranch'], 'refs/heads/infra')
  jobs:
  - job: deployinfra_prod
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'Test Bento IT - Bento EA(c5cb35bb-7864-4137-96f8-04b1a3ae2300)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'PipelinesDemo'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'template.json'
        csmParametersFile: 'parameters.json'
        deploymentMode: 'Incremental'

  - job: deployinfra_dev
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'Test Bento IT - Bento EA(c5cb35bb-7864-4137-96f8-04b1a3ae2300)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'PipelinesDemo'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'template_dev.json'
        csmParametersFile: 'parameters_dev.json'
        deploymentMode: 'Incremental'