trigger:
- master
- infra
- dev

stages:
- stage: Prod
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  jobs:
  - deployment: deployprod
    displayName: prod
    environment:
      name: PROD
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'PROD-SSH'
              contents: '**'
              targetFolder: '/home/demoadmin'
              readyTimeout: '20000'
          - task: Bash@3
            inputs:
              filePath: '/home/demoadmin/vmconfig.sh'

- stage: Dev
  condition: eq(variables['build.sourceBranch'], 'refs/heads/dev')
  jobs:
  - deployment: deploydev
    displayName: dev
    environment:
      name: DEV
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              filePath: 'vmconfig.sh'

- stage: Deploy
  condition: eq(variables['build.sourceBranch'], 'refs/heads/infra')
  jobs:
  - job: deployinfra_prod
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'Test Bento IT - Bento EA(c5cb35bb-7864-4137-96f8-04b1a3ae2300)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'PipelinesDemo'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'template.json'
        csmParametersFile: 'parameters.json'
        deploymentMode: 'Incremental'

  - job: deployinfra_dev
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'Test Bento IT - Bento EA(c5cb35bb-7864-4137-96f8-04b1a3ae2300)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'PipelinesDemo'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'template_dev.json'
        csmParametersFile: 'parameters_dev.json'
        deploymentMode: 'Incremental'